# Image de base
FROM node:20-slim AS base

# Répertoire de travail
WORKDIR /app

# Installe les dépendances système (libvips pour Sharp)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libvips libvips-dev \
    && rm -rf /var/lib/apt/lists/*

# Copie des fichiers de dépendances pour tirer parti du cache Docker
COPY package*.json ./

# Installation de toutes les dépendances (y compris dev)
RUN npm install

# Copie du reste du code
COPY . .

# Installation de nodemon globalement
RUN npm install -g nodemon

# Variables d’environnement
ENV NODE_ENV=development
ENV PORT=8080

# Expose le port
EXPOSE 8080

# Commande par défaut : nodemon (auto-restart)
CMD ["nodemon", "--legacy-watch", "server.js"]
